# Generated by Django 3.1.2 on 2020-10-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(default='', max_length=50, verbose_name='Email'),
        ),
    ]
