# Generated by Django 3.1.2 on 2020-10-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_carousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Карусель', 'verbose_name_plural': 'Карусель'},
        ),
    ]
