# Generated by Django 3.1.2 on 2020-10-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_auto_20201026_0913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
