# Generated by Django 3.1.2 on 2020-10-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_auto_20201026_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(choices=[('Россия', 'Россия'), ('Другие страны', 'Другие страны')], default='Россия', max_length=100, verbose_name='Куда')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставка',
            },
        ),
    ]
