# Generated by Django 3.1.2 on 2020-10-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0009_auto_20201030_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
