# Generated by Django 3.1.2 on 2020-10-31 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0010_auto_20201030_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
