# Generated by Django 3.1.2 on 2020-10-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0012_auto_20201031_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='track_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Трек номер'),
        ),
    ]
