# Generated by Django 3.1.2 on 2020-11-05 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0013_auto_20201031_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='top',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='button',
            name='image',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='image',
        ),
        migrations.RemoveField(
            model_name='top',
            name='image',
        ),
        migrations.CreateModel(
            name='GalleryInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('top', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Application.top')),
            ],
        ),
    ]
