# Generated by Django 3.1.2 on 2020-11-06 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0015_auto_20201106_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('top', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Application.top')),
            ],
        ),
    ]
