# Generated by Django 3.1.2 on 2020-11-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0016_imagetop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='image',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='image',
        ),
        migrations.RemoveField(
            model_name='top',
            name='image',
        ),
    ]
