# Generated by Django 3.1.2 on 2020-11-06 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0017_auto_20201106_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetop',
            name='top',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Application.top'),
        ),
    ]
