# Generated by Django 3.1.2 on 2020-11-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0019_temporarybanip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryBanIp',
        ),
    ]
