# Generated by Django 3.1.2 on 2020-11-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0020_delete_temporarybanip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagetop',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='imagetop',
            name='images',
            field=models.FileField(upload_to='images/', verbose_name='Изображение'),
        ),
    ]
