# Generated by Django 3.1.2 on 2020-11-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0021_auto_20201111_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='customer',
            name='index',
            field=models.CharField(default='', max_length=255, verbose_name='Индекс'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='', max_length=255, verbose_name='Фамилия'),
        ),
    ]
