# Generated by Django 3.1.2 on 2020-11-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0022_auto_20201115_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='index',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='index',
            field=models.CharField(default='', max_length=255, verbose_name='Индекс'),
        ),
    ]
