# Generated by Django 3.1.2 on 2020-11-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0023_auto_20201115_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='where',
            field=models.CharField(choices=[('Россия', 'Россия'), ('Другие страны', 'Другие страны'), ('Самовывоз из Москвы', 'Самовывоз из Москвы')], default='Россия', max_length=100, verbose_name='Куда'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='Application.customer', verbose_name='Покупатель (Заказчик)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('Россия', 'Россия'), ('Другие страны', 'Другие страны'), ('Самовывоз из Москвы', 'Самовывоз из Москвы')], default='Россия', max_length=100, verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя (Получатель)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия (Получатель)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон (Заказчика)'),
        ),
    ]
