# Generated by Django 3.1.2 on 2021-01-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0025_order_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cort',
            field=models.ManyToManyField(related_name='cort', to='Application.Cart', verbose_name='Содержимое корзины'),
        ),
    ]
