# Generated by Django 3.1.2 on 2021-03-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0030_auto_20210307_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_cart', to='Application.CartProduct'),
        ),
    ]
