# Generated by Django 3.1.2 on 2021-03-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0031_auto_20210308_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='Application.CartProduct'),
        ),
    ]
