# Generated by Django 3.1.2 on 2021-03-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0032_auto_20210308_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cort',
            field=models.ManyToManyField(related_name='cort', to='Application.CartProduct', verbose_name='Содержимое корзины'),
        ),
    ]
